name = "AIRAC"
uuid = "00c9ed9b-6f42-40f4-baa2-baa5a6d924cd"
authors = ["Sébastien Celles <s.celles@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
